all:	SLLTests Palindromes

Palindromes:	Palindromes.cpp
	g++ -std=c++11 -Wall -I ../doctest -DDOCTEST_CONFIG_DISABLE Palindromes.cpp -o Palindromes

SLLTests:	SLLTests.cpp
	g++ -std=c++11 -Wall -I ../doctest -DDOCTEST_CONFIG_IMPLEMENT_WITH_MAIN SLLTests.cpp -o SLLTests

clean:
	rm Palindromes SLLTests
