all:	SimpleSLLTests

SimpleSLLTests:	SimpleSLLTests.cpp
	g++ -std=c++11 -Wall -I ../../doctest -DDOCTEST_CONFIG_IMPLEMENT_WITH_MAIN SimpleSLLTests.cpp -o SimpleSLLTests

clean:
	rm SimpleSLLTests
