all:	AirlinePassenger

AirlinePassenger:	AirlinePassenger.cpp
	g++ -std=c++11 -Wall -I ../../doctest -DDOCTEST_CONFIG_DISABLE AirlinePassenger.cpp -o AirlinePassenger

clean:
	rm AirlinePassenger
